name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) check out source
      - uses: actions/checkout@v4

      # 2) install Node 18
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) install deps & build
      - run: npm ci
      - run: npm run build

      # 4) deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}
          projectId: rsvp-project-b89af
